export const traits = [
    "Adventurous",
    "Clean",
    "Good listener",
    "Honest",
    "Humorous",
    "Inspiring",
    "Kind",
    "Knowledgeable",
    "Non-judgemental",
    "Spontaneous",
    "Talkative",
    "Thoughtful",
    "Trustworthy",
  ]